<a href="https://colab.research.google.com/github/BeeramVineethReddy/Geno_Intern/blob/master/green_pixels.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import cv2

img = cv2.imread('tile.png')


In [ ]:
from matplotlib import pyplot as plt

plt.imshow(img)

plt.show()

In [ ]:
import numpy as np
rgb = np.array(img)

In [ ]:
#print(rgb)
shape=np.shape(rgb)
#print()
rows = shape[0];
cols = shape[1];

[[[239 200 229]
  [240 206 231]
  [241 214 235]
  ...
  [239 189 233]
  [241 189 235]
  [243 189 236]]

 [[246 206 236]
  [245 211 238]
  [244 216 238]
  ...
  [243 193 238]
  [243 188 236]
  [241 183 233]]

 [[245 205 237]
  [244 209 236]
  [241 211 234]
  ...
  [236 186 233]
  [238 183 231]
  [239 181 231]]

 ...

 [[232 187 228]
  [235 189 231]
  [236 191 232]
  ...
  [243 192 234]
  [245 195 235]
  [246 197 235]]

 [[232 185 229]
  [233 186 230]
  [233 185 231]
  ...
  [244 196 236]
  [244 197 235]
  [244 197 234]]

 [[232 185 232]
  [233 184 232]
  [232 183 231]
  ...
  [240 193 231]
  [237 191 228]
  [234 189 226]]]



In [ ]:
ans = []
for i in range(rows):
  for j in range(cols):
    if(rgb[i][j][1]>252):
      ans.append([i,j])
    #print(rgb[i][j])

In [ ]:
ans

[[50, 269],
 [50, 270],
 [50, 271],
 [50, 272],
 [50, 273],
 [51, 268],
 [51, 269],
 [51, 270],
 [51, 271],
 [51, 272],
 [51, 273],
 [51, 274],
 [51, 275],
 [52, 268],
 [52, 269],
 [52, 270],
 [52, 271],
 [52, 272],
 [52, 273],
 [52, 274],
 [52, 275],
 [52, 276],
 [53, 267],
 [53, 268],
 [53, 269],
 [53, 270],
 [53, 271],
 [53, 272],
 [53, 273],
 [53, 274],
 [53, 275],
 [53, 276],
 [53, 277],
 [53, 278],
 [54, 265],
 [54, 266],
 [54, 267],
 [54, 268],
 [54, 269],
 [54, 274],
 [54, 275],
 [54, 276],
 [54, 277],
 [54, 278],
 [54, 279],
 [54, 280],
 [55, 264],
 [55, 265],
 [55, 266],
 [55, 267],
 [55, 268],
 [55, 269],
 [55, 274],
 [55, 275],
 [55, 276],
 [55, 277],
 [55, 278],
 [55, 279],
 [55, 280],
 [55, 281],
 [55, 282],
 [55, 283],
 [56, 264],
 [56, 265],
 [56, 266],
 [56, 267],
 [56, 268],
 [56, 277],
 [56, 278],
 [56, 279],
 [56, 280],
 [56, 281],
 [56, 282],
 [56, 283],
 [56, 284],
 [57, 264],
 [57, 265],
 [57, 266],
 [57, 267],
 [57, 280],
 [57, 281],
 [57, 282],
 [57, 283],
 [57